### ISSUE TITLE
AFLplusplus wants you

### ISSUE THREAD

**Issue by andreafioraldi** [puppet-meteor/MOpt-AFL#1]
Hi guys,
you have done a very cool work congratulations.
I'm here to ask if you want to contribute to https://github.com/vanhauser-thc/AFLplusplus and submit a pull request including your changes to AFL.
AFL++ is a the son of AFL (the lastest change to AFL is at least 2 years ago) which merges all the best features independently added to AFL in recent years in a single implementation.
The results in the paper are awesome and I'd like to see this technique merged so that all the best of the AFL family can live in a single repo and avoid fragmentation.

Thanks,
Andrea

**Comment by vanhauser-thc** [comment]
@andreafioraldi - you are too late, its already in afl++ :) it had its own branch 7 days ago and joined it into master/trunk before the weekend :)

MOpt is really good

**Comment by andreafioraldi** [comment]
Ah lol I missed it, GG
