### ISSUE TITLE
SmartSeed source code missing

### ISSUE THREAD

**Issue by BinaryResearch** [puppet-meteor/MOpt-AFL#2]
In the paper "SmartSeed: Smart Seed Generation for EfficientFuzzing", it is stated that 

> We  also  make  our  system  publicly  available  to  facilitate  the  research  in this area, which is available at: https://github.com/puppet-meteor/SmartSeed

However, this still has not been done. Do you still plan to do so?

**Comment by puppet-meteor** [comment]
Hi, at 'https://github.com/puppet-meteor/SmartSeed' we state that we will update the public code when our paper is accepted, unfortunately the reviewers seem not to be interested in SmartSeed.

**Comment by BinaryResearch** [comment]
谢谢您的回复. 虽然他们对您们的研究不感兴趣,可是我很希望您们决定发布代码.除了我以外, 很多人还觉得SmartSeed是一个很有趣的主意. 那些reviewers这次也许是错的.

It is deeply unfortunate that they are not interested. Even if the reviewers are not interested in SmartSeed, others including myself are very interested. If your results are reproducible, then SmartSeed has scientific merit, no matter what anyone says. I hope you will decide to release the code publicly, so that all may benefit from your innovation. It may spur further advancements in this field. At the very least, it will save others from having to independently re-do the hard work you already have done.

对了, 如果您们在中国,我希望您们和您们的家人都还是又健康又安全. Chen Jing是武汉大学的, 对吧? 武汉加油!

**Comment by puppet-meteor** [comment]
Thanks! While I don't have the plan to open source SmartSeed recently. Its performance is acceptable in 2018, but is not good enough for now. Maybe I will update the better version of SmartSeed in the future.

**Comment by BinaryResearch** [comment]
Ok, understood. Good luck with your research.
