### ISSUE TITLE
Compilation fails when using LLVM 9

### ISSUE THREAD

**Issue by lromerio** [puppet-meteor/MOpt-AFL#3]
When compiling with LLVM 9, the post build tests contained in `llvm_mode/Makefile` are failing. It is a known problem that has been fixed in the AFL repository.

Comment explaining the problem: https://github.com/google/AFL/issues/30#issuecomment-530716446
Commit fixing the problem: https://github.com/google/AFL/commit/1f414d53535ea470bba3858bc1324081baf22c75

I hope this helps, I can make a pull request if needed.

**Comment by puppet-meteor** [comment]
Thanks for your help! prs are welcome!

**Comment by lromerio** [comment]
I'm happy to help! :wink:

#4 should fix the problem.
