### ISSUE TITLE
Run with "-d" parameter?

### ISSUE THREAD

**Issue by zhanggenex** [puppet-meteor/MOpt-AFL#6]
Hi, I looked into the code and noticed that MOpt changes **no** codes in the deterministic mutation stage. Is it true that we should run MOpt with "-d" that skip the deterministic stage?
Thanks

**Comment by puppet-meteor** [comment]
Hi, if you have read our paper, you may notice that we analyze the influence of the deterministic stage on MOpt and provide the pacemaker fuzzing mode to accelerate the convergence if necessary. Thus, you do not need to use "-d" parameter. 

When enter the pacemaker fuzzing mode, you may notice that MOpt skip the deterministic stage. If you adjust the "limit_time_bound" parameter in the source code, MOpt will selectively skip and reuse the deterministic stage. 

We are not recommended to directly skip the determinsitic stage, which may perform better in the short term while lose the part of mutation operators in the long term.
