### ISSUE TITLE
fuzz w3m with MOpt timeout

### ISSUE THREAD

**Issue by imbawenzi** [puppet-meteor/MOpt-AFL#7]
When I fuzz w3m with MOpt and also AFL, it always timeout, do you meet the same problem?
please help, thank you!
the commond I use is shown above, and my os is Ubuntu 18.04
```shell
git clone https://github.com/tats/w3m.git
cd w3m
./configure
make
afl-fuzz -Q -i path/to/input/dir -o path/to/output/dir path/to/w3m @@
```
then the output is
```
[-] The program took more than 1000 ms to process one of the initial test cases.
    This is bad news; raising the limit with the -t option is possible, but
    will probably make the fuzzing process extremely slow.

    If this test case is just a fluke, the other option is to just avoid it
    altogether, and find one that is less of a CPU hog.

[-] PROGRAM ABORT : Test case 'id:000000,orig:0.txt' results in a timeout
         Location : perform_dry_run(), afl-fuzz.c:2823
```

**Comment by imbawenzi** [comment]
using afl-gcc to compile and run will have the same result, the exec speed is too slow
```
len = 2179, map size = 1324, exec speed = 292812 us
```
I also try use `-dump` option, like
```
afl-fuzz -Q -i ~/test/input -o ~/test/output ~/test/MOpt/w3m/w3m -dump @@
```
it still timeout, but when I run commond
```
./w3m -dump 0.txt 
```
it will show  output immediately, so it is very confused

**Comment by puppet-meteor** [comment]
Hi, if you read README of AFL carefully, you can realize that AFL provides the timeout setting.  You may use 
`afl-fuzz  -i path/to/input/dir -o path/to/output/dir   -t 500+ -m 5000 path/to/w3m @@`

![image](https://user-images.githubusercontent.com/17903718/102996702-870dc100-455e-11eb-9fb6-e39d94b49382.png)

**Comment by imbawenzi** [comment]
Thank you very much for help!
anthor question is all of the seed in dir `/seed sets/100 seeds/objdump_seed/` is  shell script
but the `objdump`'s input should be binary, like in `/seed sets/20 seeds/objdump_seed/` and `/seed sets/200 seeds/objdump_seed/`

**Comment by puppet-meteor** [comment]
Hi, this may be the mistake. 
Since we try to employ different files as the inital seed sets to evaluate the performance of each fuzzer, and the shell script still can trigger the unique paths of objdump,  I think it is ok :D
